# Generated by Django 2.2.6 on 2026-09-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='mobile_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
