# Generated by Django 2.2.6 on 2026-09-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20260929_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='specialisation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
